<?php
return [
    "100"   =>  "Continue",
    "101"   =>  "Switching Protocols",
    "102"   =>  "Processing",

    "200"   =>  "OK",
    "201"   =>  "Created",
    "202"   =>  "Accepted",
    "203"   =>  "Non-Authoritative Information",
    "204"   =>  "No Content",
    "205"   =>  "Reset Content",
    "206"   =>  "Partial Content",

    "300"   =>  "Multiple Choices",
    "301"   =>  "Moved Permanently",
    "302"   =>  "Found",
    "303"   =>  "See Other",
    "304"   =>  "Not Modified",
    "305"   =>  "Use Proxy",
    "306"   =>  "Switch Proxy",
    "307"   =>  "Temporary Redirect",

    "400"   =>  "Bad Request",
    "401"   =>  "Unauthorized",
    "402"   =>  "Payment Required",
    "403"   =>  "Forbidden",
    "404"   =>  "Not Found",
    "405"   =>  "Method Not Allowed",
    "406"   =>  "Not Acceptable",
    "407"   =>  "Proxy Authentication Required",
    "408"   =>  "Request Time-out",
    "409"   =>  "Conflict",
    "410"   =>  "Gone",
    "411"   =>  "Length Required",
    "412"   =>  "Precondition Failed",
    "413"   =>  "Request Entity Too Large",
    "414"   =>  "Request-URI Too Large",
    "415"   =>  "Unsupported Media Type",
    "416"   =>  "Requested range not satisfiable",
    "417"   =>  "Expectation Failed",
    "421"   =>  "There are too many connections from your internet address",
    "422"   =>  "Unprocessable Entity",
    "423"   =>  "Locked",
    "424"   =>  "Failed Dependency",
    "425"   =>  "Unordered Collection",
    "426"   =>  "Upgrade Required",
    "449"   =>  "Retry With",

    "500"   =>  "Internal Server Error",
    "501"   =>  "Not Implemented",
    "502"   =>  "Bad Gateway",
    "503"   =>  "Service Unavailable",
    "504"   =>  "Gateway Time-out",
    "505"   =>  "HTTP Version Not Supported",
    "506"   =>  "Variant Also Negotiates",
    "507"   =>  "Insufficient Storage",
    "509"   =>  "Bandwidth Limit Exceeded",
    "510"   =>  "Not Extended",

    "600"   =>  "Unparseable Response Headers",

    "1111"  =>  "YangRAM Status Message",

    "1200"  =>  "Welcome",
    "1201"  =>  "Create Successed",
    "1202"  =>  "Done",
    "1203"  =>  "Update Successed",
    "1204"  =>  "Remove Successed",
    "1212"  =>  "Delete Successed",

    "1400"  =>  "Initialized Failed",
    "1401"  =>  "Create Failed",
    "1402"  =>  "Unexpected Access",
    "1403"  =>  "Update Failed",
    "1404"  =>  "Remove Failed",
    "1412"  =>  "Delete Failed",

    "1410"  =>  "Operation Illegal",
    "1411"  =>  "Authorisation Error",
    // "1411.0"  =>  "Login Error",
    // "1411.1"  =>  "No permissions to create resource.",
    // "1411.2"  =>  "No permissions to read resources.",
    // "1411.3"  =>  "No permissions to update resource.",
    // "1411.4"  =>  "No permissions to delete resource.",
    // "1411.5"  =>  "No permissions to access appointed database table.",
    // "1411.6"  =>  "No permissions to write data to appointed database table.",
    // "1411.7"  =>  "No permissions to write data to file.",
    "1412"  =>  "System Error",
    "1413"  =>  "Operation Error",
    "1414"  =>  "Error",
    "1415"  =>  "Parameters Given Error",
    "1416"  =>  "SQL Error",
    "1417"  =>  "Connect Error",
    "1418"  =>  "Error Model Property Value Given",

    "1420"  =>  "Unknow",
    "1421"  =>  "System Be Tampered",
    "1422"  =>  "Application Files Be Tampered",

    "1440"  =>  "Not Found",
    "1441"  =>  "Application Not Found",
    "1442"  =>  "Module Or Component Not Found",
    "1443"  =>  "Properties Or Attributes Not Found",
    "1444"  =>  "Files Of Application Not Found",
    
    "1460"  =>  "System Encountered Abnormal Data",
    "1461"  =>  "Unexpected Application Data",
    
    "1500"  =>  "Low PHP Version",
    "1501"  =>  "PHP Extension Not Found",
];